### PR TITLE
[Feature]Add bash script to simplify file regrid

### PR DESCRIPTION
**Pull request by Jourdan-He**
Implement a bash script that combines gridspec-create and ESMF_RegridWeightGen into one step.

### CODE REVIEW

**Comment by Jourdan-He** [comment]
Right now the pre_regrid.sh is only capable of producing latlon grids of 2x2.5 and 4x5. The script is executable, but have not tested the accuracy of the output.

**Comment by kilicomu** [comment]
Hi @Jourdan-He - I'm not sure that this bash script is the right way to go towards fixing the stretched grid regridding. It is less flexible than calling `gridspec` and `ESMF_RegridWeightGen` directly, and further obfuscates that process.

I wonder if for now this could just be a documentation change? With the updated `regrid_restart_file.py` it really only needs a short amount of documentation to go through a full regridding that I've tested and works.

I am happy to make that documentation once #190 has been reviewed, I just don't want to write full docs for something that might need to change.

I'm also happy to properly integrate `gridspec` and `ESMF_RegridWeightGen` into a GCPy module, I just can't make time to do that right now!

**Comment by lizziel** [comment]
Hi @Jourdan-He, it's confusing there are now two PRs for regridding. Is the PR from @kilicomu okay to merge in as is? As @kilicomu said, maybe all we need is to add documentation? If yes, could we merge his PR and then add documentation in a separate PR?

**Comment by kilicomu** [comment]
@lizziel Agree on the two PRs being confusing also! I'll be happy to add documentation once somebody else has tested my `regrid_restart_file.py`, and I'll do that in a separate PR.

**Comment by Jourdan-He** [comment]
Hi @lizziel @kilicomu , sorry about the confusion, I meant that for the latlon grid, it is quite limited in terms of resolution. However, it is capable of any gcs or sgcs grids. I haven't tested that PR though, so I am not sure about if it's okay to merge now. I mainly focused on the last paragraph of @kilicomu 's PR...

**Comment by kilicomu** [comment]
@Jourdan-He I think the nicer longer-term solution for the regridding will be to integrate into GCPy as a module, like the old regridding method, as opposed to adding e.g. extra shell scripts.

#190 is intended to provide a short-term solution, with some documentation, until I can make time to write up that module. I will be able to make time soon!

**Comment by Jourdan-He** [comment]
@kilicomu I agree. I created this PR based on my misunderstanding, so I'll close it now.

**Pull request closed without merging**
