### PR TITLE
Feature/benchmarks configurable yaml file

### PR DESCRIPTION
**Pull request by laestrada**
@yantosca For the structure of the yaml configuration file I tried to follow a similar pattern as used in compare_diags.yml. The primary sections being divided by ref and dev with further subdivision based on whether it is gcc or gchp. 

Currently, I have a single config file with different sections for 1mon, 1yr, and 1yr_tt benchmarks, but am happy to split it into a single file for each benchmark type if you feel strongly about it?

I didn't make any significant attempt to modularize the scripts or separate sections into discrete functions as I think this will be done as part of #102

### CODE REVIEW

**Review by yantosca — COMMENTED** [review]
This looks good.  @laestrada, have you tested this with the gcpy_test data?

**Comment by laestrada** [comment]
> This looks good. @laestrada, have you tested this with the gcpy_test data?

@yantosca I tested the 1mon run script to completion. For the 1yr_fullchem and 1yr_tt, I ran it for an hour for each as basic sanity checks, but I can submit jobs to do a full test of of these two.

**Comment by msulprizio** [comment]
@laestrada I realize this PR has already been merged, but I am trying the new setup today and noticed the instructions at the top of `run_1mo_benchmark.py` are outdated. Specifically:

```
You can customize this by editing the following settings in the
"Configurables" section below:

    (1) Edit the path variables so that they point to folders w/ model data
    (2) Edit the version strings for each benchmark simulation
    (3) Edit the switches that turn on/off creating of plots and tables
    (4) If necessary, edit labels for the dev and ref versions
```

Could these please be modified to instruct users to also copy the YML file and update settings there? The same may also apply for the headers in the other benchmark scripts.

**Comment by msulprizio** [comment]
I would also suggest separating `benchmarks.yml` into three separate YML files -- one for 1-month, one for 1-year fullchem, 1 for 1-year transport tracers. The existing file now is quite busy, and these simulations don't depend on one another so it would make sense to split up.

**Pull request merged**
