### PR TITLE
Additional cleanup of gcpy routines

### PR DESCRIPTION
**Pull request by yantosca**
This PR updates `benchmark.py`, `util.py`, and `plot.py`.  Several suggestions from the `pylint` linter were incorporated, including:

- Converting string `.format()` statements to f-strings
- Using `isinstance` for type checking
- Removing `else` blocks after `return` or `raise` 
- Trimming whitespace
- Abstracting YAML input to `util.read_config_file`
- Abstracting directory creation in `benchmark.py` to `make_directory`
- etc.

This PR should be merged after #200

### CODE REVIEW

**Comment by yantosca** [comment]
I have also added some formatting fixes for the benchmark tables to prevent long version strings from being added in the headers.

**Comment by yantosca** [comment]
In commit 0334759 we now place a newline character in the middle of the diff-of-diffs refstr and devstr, if the string would be longer than 40 characters.  This prevents the title strings in the top row of diff-of-diffs plots from overlapping each other.  This is a "cheap" solution as it is done outside of the plotting routines, but at least you can now make out the version strings (which get quite long for the automated cloud benchmarks).

Sample output:
dod

**Comment by yantosca** [comment]
This PR closes #188 as well.

**Review by msulprizio — APPROVED** [review]
These updates look good to merge.

**Pull request merged**
